services:
  postgres-dev:
    container_name: postgres-local-dev
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password}
      POSTGRES_DB: ${POSTGRES_DB:-dev_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - dev-network
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-dev_db}' ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'

networks:
  dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
